# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------

ssl_certificate_key <%= certs_dir %>/<%= private_domain %>_ecc/<%= private_domain %>.key;
ssl_trusted_certificate <%= certs_dir %>/<%= private_domain %>_ecc/<%= private_domain %>.cer;