#!/bin/bash
set -e
script_dir=$(dirname $(readlink -f $0))
cd $script_dir
if [ -f /etc/drumee/drumee.sh ]; then
  source /etc/drumee/drumee.sh
  app_user=$DRUMEE_SYSTEM_USER
else
  echo Looks like Drumee infrastructure is not yet configured
  exit 1
fi

#Ensure db server to log here, whatever OS log style
mysql_dir=/var/log/mysql
mkdir -p $mysql_dir
touch $mysql_dir/error.log
chown -R mysql:mysql $mysql_dir

mkdir -p $DRUMEE_DB_DIR/run
mariadb-install-db --user=mysql --basedir=/usr --datadir=$DRUMEE_DB_DIR
service mariadb start

exists=$(mariadb -e "SHOW GRANTS FOR '$app_user'@'localhost';"| grep unix_socket | tail -1)
if [ "$exists" = "" ]; then
  echo Creating DB USER "'$USER'@'localhost'"
  mariadb -e "CREATE OR REPLACE USER '$app_user'@'localhost' IDENTIFIED VIA unix_socket"
  mariadb -e "GRANT ALL PRIVILEGES ON *.* TO '$app_user'@'localhost'"
else
  echo $app_user already exists, skipped
fi

collation=$(mariadb -e "show variables like 'character_set_collations';"|tail -1)
if [ "$collation" != "" ]; then
  mariadb -e "set GLOBAL character_set_collations='utf8mb4=utf8mb4_general_ci'"
fi

cd templates/seed
for file in $(ls *.sql); do
  db_name=$(echo $file | sed -E "s/\.sql$//")
  out=$(mariadb -e "SHOW databases like '${db_name}'" | tail -1)
  if [ "$out" = "" ]; then
    echo Polutating $db_name
    mariadb -e "CREATE database ${db_name}" 
    mariadb -e "ALTER DATABASE ${db_name} COLLATE 'utf8mb4_general_ci'"
    mariadb $db_name < $file
  else
    echo $db_name already exists, skipped
  fi
done