#!/bin/bash
# This script in intended to run within container
set -e
script_dir=$(dirname $(readlink -f $0))
envfile=/etc/drumee/drumee.sh

if [ "$USER" = "" ];then
  export USER=$(whoami)
fi

start_daemons() {
  source $envfile 
  if [ ! -d $DRUMEE_DATA_DIR ]; then
    echo Data dir $DRUMEE_DATA_DIR not found.
    exit 1
  fi 

  data_owner=$(stat -c '%U' $DRUMEE_DATA_DIR)
  if [ "$DRUMEE_SYSTEM_USER" != "$data_owner" ]; then
    chown -R $DRUMEE_SYSTEM_USER:$DRUMEE_SYSTEM_GROUP $DRUMEE_DATA_DIR
  fi

  service mariadb start
  service nginx start
  service redis-server start
  pm2 restart $DRUMEE_SERVER_HOME/ecosystem.config.js
}

if [ -f $envfile ]; then
  echo Drumee is already configured. Staring daemons
  start_daemons
  exit 0
fi

# cd $script_dir
# node setup-infra/index.js --localhost=1 --db-dir=/var/lib/drumee/db --reconfigure=1 \
#   --watch-dirs=/var/lib/drumee/runtime/server,/var/lib/drumee/runtime/ui

# if [ -f $envfile ]; then
#   source $envfile 
#   mkdir -p $DRUMEE_DB_DIR/run
#   schemas/populate
#   node schemas/index.js
#   start_daemons
# else
#   echo "Could not start Drumee. $envfile not found"
# fi
