#!/bin/bash
# This script in intended to run within container
set -e
script_dir=$(dirname $(readlink -f $0))
envfile=/etc/drumee/drumee.sh

if [ ! -f $envfile ]; then
  $script_dir/configure
fi

if [ "$USER" = "" ];then
  export USER=$(whoami)
fi

start_daemons() {
  source $envfile 
  if [ ! -d $DRUMEE_DATA_DIR ]; then
    echo Data dir $DRUMEE_DATA_DIR not found.
    exit 1
  fi 

  data_owner=$(stat -c '%U' $DRUMEE_DATA_DIR)
  if [ "$DRUMEE_SYSTEM_USER" != "$data_owner" ]; then
    chown -R $DRUMEE_SYSTEM_USER:$DRUMEE_SYSTEM_GROUP $DRUMEE_DATA_DIR
  fi

  service mariadb start
  service nginx start
  service redis-server start
  pm2 restart $DRUMEE_SERVER_HOME/ecosystem.config.js
}

if [ -f $envfile ]; then
  echo Drumee is already configured. Staring daemons
  start_daemons
  exit 0
else
  echo Ooop looks like Drumee has not been properlt confured
fi
